### ISSUE TITLE
Ligature support

### ISSUE THREAD

**Issue by kilburn** [cmuratori/refterm#10]
Many programming-oriented monospace fonts include ligatures for combinations of ASCII characters (see https://github.com/tonsky/FiraCode for an example).

The "ascii character glyph cache" approach used here seems to be incompatible with such ligatures. Could this approach produce correct ligature glyphs while maintaining the same performance or is this something that needs to be sacrificed for this rendering algorithm to work?

**Comment by cmuratori** [comment]
There is no "ASCII character glyph cache" in this system.  The cache supports arbitrarily complex input sequences and arbitrarily long output sequences, including all of Unicode and anything else you may want to cache.

It also supports reserved slots for sequences you want to handle manually, so if you want to do something like handle a subset of glyphs via direct lookup to avoid traversing the actual cache, you can do that, too.  The example program does this for the printable ASCII range as a demonstration of direct lookups.  This is purely optional, of course, as is the choice of the ASCII range. You could choose to direct map any part of the input space that you choose.

Programming ligatures are thus fully supported both ways, as is Arabic, diacritical-on-ASCII, Hangul, etc.

\- Casey

**Comment by kilburn** [comment]
Ok, so if I understand correctly:

- I could expect the performance to be worse if I disabled the ASCII range direct lookup part
- It is the application's job to detect codepoint chunks that it wants to map directly and pass those to the renderer
- The renderer would not support non-monospace fonts

Have I misunderstood something? Thanks for the explanation!

**Comment by cmuratori** [comment]
Roughly speaking, yes.  For clarification:

* The difference between direct mapped vs. full cache on my machine is ~7000fps vs. ~4000fps.  So there is a "big difference" in the sense that you do get a nice win from direct mapping.  But, it's also already 4000fps without direct mapping, so, you probably don't care :)  Plus, this does not affect the ingress speed, just the rendering speed, so the 1gb file still has a throughput of 2s on fast pipe either way.
* Yes, the application can decide when to and not to use the cache. At initialization time, you just say how many slots you want to reserve for your own use. You can then map those however you want. In the current example code, it just maps printable ASCII. But you could instead map other ranges, using any kind of mapping you want, since the cache does not care.
* I'm not sure what you mean exactly by "the renderer would not support non-monospace fonts". The HLSL shader is intentionally a tile-based shader, because that was the point of the exercise. However, the cache system itself actually doesn't care whether the fonts are proportional or not. So if you wanted to use proportional fonts, you would definitely want to modify the HLSL shader to use a different lookup, the cache would actually not need to be modified unless you were worried about the space wasted by not trimming cache elements to characters.

\- Casey
