### ISSUE TITLE
Consider a more permissive license so the folks at MS can use your PhD dissertation

### ISSUE THREAD

**Issue by crozone** [cmuratori/refterm#17]
For example, MIT.

I don't know what ideological stance you have on licensing your code, but it would certainly be nice if the Windows Terminal team were able to improve their renderer based on at least the technique demonstrated in your project. I think it benefits every Windows user if the official Windows Terminal is able to be improved from the baseline you have laid out here.

As it stands, the legal prickliness of GPL and the minefield of what constitutes derivative work means that MS employees, and indeed any other non-GPL codebase, are unable to even glance at your code. I'm sure you are aware of this spicy discussion:

https://github.com/microsoft/terminal/issues/10462#issuecomment-873515286

Microsoft will certainly be able to eventually implement a cleanroom solution, and yes, they are a billion dollar company that should have no issue writing their own code. It nevertheless seems a shame that the license is an impediment to the progress of a program used by many.

Best regards.

**Comment by cmuratori** [comment]
If Microsoft wants to use the code they are welcome to pay for it.  I find it somewhat off-putting to suggest that people should do all the work for Microsoft for free, _and then_ cater to Microsoft's licensing needs.

\- Casey

**Comment by crozone** [comment]
After reading the responses you received in https://github.com/microsoft/terminal/issues/10362 I think I understand your position a little better and your frustration with the terminal team. The suggestion that performant terminal rendering requires a "an entire doctoral research project in performant terminal emulation" is somewhat laughable.

Nevertheless, the terminal rendering technique that you have developed (glyph alias lookup in a GPU shader), while apparently obvious to you, many graphics programmers, and anyone familiar with GPU shaders, is novel enough to the world of terminal emulation that AFAICT it has never been implemented in another terminal emulator, in Linux, macOS, or Windows, despite its apparent simplicity. In fact your terminal renderer, despite being an "unoptimised baseline", manages to beat out the performance of basically every other software based terminal renderer that currently exists on modern operating systems. Your codebase constitutes valuable original research.

>
> I find it somewhat off-putting to suggest that people should do all the work for Microsoft for free, and then cater to Microsoft's licensing needs.
>

Well it depends on your motivations. If you want to improve Windows Terminal, like many of the other non-MS contributors to the project, that's the nature of the beast. On the other hand, if you just want to prove a point and leave, GPLv2 is certainly an effective way to do that. More power to you, and I can't really blame you given their responses.

**Comment by cmuratori** [comment]
Well, prove-a-point-and-leave for sure, but more broadly, I would like people who work on competing free software to be able to use this.  So I would be delighted if anyone in the Linux world, where many things are GPLv2 or GPLv3, would borrow something useful from this codebase if they could make good use of it.

Separately, I just like doing it for my own education.  In the course of doing this project, I learned DirectWrite, D3D11, Uniscribe, named pipes, and IME integration already :)

\- Casey

**Comment by debugnik** [comment]
@cmuratori You should at least clarify in the README if you intend the license to be "GPLv2 only" or "GPLv2 or any later version". The license requires a separate notice for the latter.

**Comment by dmitry-azaraev** [comment]
GPL isstupid decision. No one need license for know how parse and render streams. This repository solces non existent task, and someone should get PhD for thing which not related to science.

**Comment by NeKJ** [comment]
It is obvious, Casey, that you are a true elite programmer (in the good sense), which you are "orders of magnitude" (to reuse this, frequently used in this matter, phrase) better, in every way, compared to anyone in the WT team. 
It is obvious, because you spotted an important problem in their project and you immediately knew the solution for. And that you also didn't badge a notch, despite the heat you got, because your arguments were firmly based on in-depth knowledge, complete understanding of the domain and on firm logic. And no one can ever win against logic, no matter what they try.

It is obvious how good you are, also because you actually provided a no-doubt proof by sitting down, putting the time,.effort and skills and building a complete proof of concept that demonstrated every claim you made.

It really saddens me, that in order for an otherwise well intenioned team working on a big and geeat company, whom are paid handsomely, had to take such an elite programmer to actually sit down and demonstrate to them, like a 1st grade teacher, step by step how it is done.

Now to be clear, I am sure all of the members in WT team are good willing and competent programmers and I believe they want to do the best they can for the project. And they did actually admitted they were wrong and they are now attempt to fix it using the correct approach. That's good.

But, it is obvious, at least to me, that if you hadn't gone to such  lengths to prove beyond any doubt, how wrong they were, they wouldn't ever do anything to fix the problem.

And that is the part that disappoints me in the grand scheme of things. I now wonder, what will happen in the next problem they will face? Will they have the same attitude or will they actually sit down to learn and do the necessary work to fix it? 
Will it take yet another elite programmer to make a POC program for them to be convinced? And to be honest, I can't verify if they got convinced by the actual POC and code or they simply had to pull back because of all the backlash they got and which probably has upset someone else in MS, and forced them to backtrack and approach you?

I hope it is the first, but now we can never know.

I don't know you, but I am proud of you of how you handled this, especially by making sure your code will not be used by them in any way, and that you demand to get paid if they wish to.

This incident, is a remarkable real world example of the Dunning-Kruger effect. It is actually, very poignant in illustrating how much of an impact this effect has and how many problems could be avoided if it was mitigated. Of course, you are the actual top expert in this case and they are the low-to-mid level ones.

I am impressed and I support you 100% with how you handled this and the choices you made.

I am actually amazed why MS hasn't hired you yet, to be honest. This is like a no-brainer for them, and I don't think that a multibillion $ corp can't make an irresistible offer.

Congrats to you, and a thank you to the whole WT team for not taking my opinion too harsh and having no hard feelings about this.
